let newTestamentSort = {
	MAT: { sort: 1 },
	MRK: { sort: 2 },
	LUK: { sort: 3 },
	JHN: { sort: 4 },
	ACT: { sort: 5 },
	ROM: { sort: 6 },
	"1CO": { sort: 7 },
	"2CO": { sort: 8 },
	GAL: { sort: 9 },
	EPH: { sort: 10 },
	PHP: { sort: 11 },
	COL: { sort: 12 },
	"1TH": { sort: 13 },
	"2TH": { sort: 14 },
	"1TI": { sort: 15 },
	"2TI": { sort: 16 },
	TIT: { sort: 17 },
	PHM: { sort: 18 },
	HEB: { sort: 19 },
	JAS: { sort: 20 },
	"1PE": { sort: 21 },
	"2PE": { sort: 22 },
	"1JN": { sort: 23 },
	"2JN": { sort: 24 },
	"3JN": { sort: 25 },
	JUD: { sort: 26 },
	REV: { sort: 27},
};

module.exports = { newTestamentSort };
